model:
  type: pyramid
  depth: 272
  alpha: 200
  bottleneck: True
dataset: cifar100
aug: pba
hp_path: '/usr/share/bind_mount/scripts/MicroNet/Training/schedules/pbt_policy_cutout16_train10k.txt'
hp_epochs: 200
cutout: 16
batch: 64
epoch: 1800
lr: 0.25
alpha: 1e-5
lr_schedule:
  type: 'pyramid'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.00005