model:
  type: resnet50
dataset: imagenet
aug: inception
cutout: 0
batch: 128 # this value is only for one gpu. In our setting, we have 8 machines with 4 gpus. 128*4*8 = 4096 batch size was used.
epoch: 270
lr: 0.05
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 32
    epoch: 5
optimizer:
  type: sgd
  nesterov: False
  decay: 0.0001
  clip: 0
